export const names = [
    'Aria',
    'Kai',
    'Leona',
    'Darius',
    'Sienna',
    'Zayn',
    'Amara',
    'Elias',
    'Isla',
    'Aiden',
    'Nia',
    'Mateo',
    'Luna',
    'Caleb',
    'Zara',
    'Rafael',
    'Noor',
    'Mikaela',
    'Kian',
    'Naomi',
];
export const countries = [
    { country: 'United States', city: 'New York' },
    { country: 'Canada', city: 'Toronto' },
    { country: 'Germany', city: 'Berlin' },
    { country: 'France', city: 'Paris' },
    { country: 'United Kingdom', city: 'London' },
    { country: 'Australia', city: 'Sydney' },
    { country: 'Japan', city: 'Tokyo' },
    { country: 'Brazil', city: 'São Paulo' },
    { country: 'India', city: 'Mumbai' },
    { country: 'China', city: 'Shanghai' },
    { country: 'Mexico', city: 'Mexico City' },
    { country: 'Italy', city: 'Rome' },
    { country: 'South Africa', city: 'Cape Town' },
    { country: 'Russia', city: 'Moscow' },
    { country: 'Spain', city: 'Madrid' },
    { country: 'Turkey', city: 'Istanbul' },
    { country: 'Netherlands', city: 'Amsterdam' },
    { country: 'Argentina', city: 'Buenos Aires' },
    { country: 'South Korea', city: 'Seoul' },
    { country: 'Egypt', city: 'Cairo' },
];
export const imageUrls = [
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Aria',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Kai',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Leona',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Darius',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Sienna',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Zayn',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Amara',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Elias',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Isla',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Aiden',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Nia',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Mateo',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Luna',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Caleb',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Zara',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Rafael',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Noor',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Mikaela',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Kian',
    'https://api.dicebear.com/9.x/pixel-art/svg?seed=Naomi',
];
export const enrollmentNumbers = [
    829371, 547829, 193402, 614537, 732819, 408215, 952374, 671028, 284519,
    523476, 798654, 436729, 183947, 950263, 602817, 741926, 239548, 874251,
    596738, 328417,
];
export const subjects = ['Science', 'Arts', 'Commerce'];
export const sections = ['A', 'B', 'C', 'D', 'E'];
export const classes = ['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']